name: plant_care
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  fl_chart: ^0.65.0
  http: ^1.4.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.3
  intl: ^0.18.0
  floor: ^1.5.0
  uuid: ^4.5.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  firebase_core: ^3.4.1
  shared_preferences: ^2.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/google_logo.png
    - assets/images/pc_logo.png
    - assets/images/pc_logo_white.png